### ISSUE TITLE
中文输入法在IOS中无法使用

### ISSUE THREAD

**Issue by EveLuty** [F-loat/vue-simplemde#15]
查了很多资料，说是因为codeMirror的问题，因为他会在用户编辑组词时就更新view，导致ios中输入中文不行，始终都是直接输入了英文。

不知道你有没有解决方案呀。网上有几个思路，一个是组词时的event事件，叫做CompositionEvent。但是好像还没有完美解决方案。

开这个issue，我想提醒下作者，这里有个无法避免的问题啊，在ios中。

如果无法解决，可否提供个方法，让我们可选择不使用codeMirror，而是选择其他方式显示编辑时的输入框？比如网上能查到，自动适应高度的texteare，对于ios中，够用了。或者其他，至少能够输入中文就好。

谢谢

**Comment by F-loat** [comment]
嗯，这个问题其实应该到simplemde的仓库去反馈，我只是做了一个vue插件的封装而已，不过我可以试试看可不可以通过hack的方式来处理下这个问题。

另外高度默认就是自适应的，可以通过以下样式设置最小高度
``` css
.markdown-editor .CodeMirror, .markdown-editor .CodeMirror-scroll {
  min-height: 200px;
}
```

我的demo里是把高度设置为固定值了，所以才不会自动调整
``` css
.markdown-editor .CodeMirror {
  height: 300px;
}
```
