### ISSUE TITLE
引入了highlight对应主题的css但是没法正常显示

### ISSUE THREAD

**Issue by zhaoyn7** [F-loat/vue-simplemde#62]
引入了highlight.js然后加载到了window上：
```js
import hljs from 'highlight.js'
window.hljs = hljs
```

引入了css但是不起作用：
```css 
@import 'highlight.js/styles/atom-one-dark.css';
```

只能再引入详细的背景和字体的颜色才行：
```css
  /*修改代码块背景色及字体颜色*/
  .theme .editor-preview-side pre, .theme .editor-preview pre{
    color: #abb2bf !important;
    background: #282c34 !important;
  }
```

很喜欢这个编辑器，希望能继续维护！
